server:
  port: 8088

spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://101.200.82.237:3306/user_center?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: abc.123
    hikari:
      max-lifetime: 30000
      minimum-idle: 1
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 10000
      connection-timeout: 30000
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
