
spring:
  application:
    name: user-center


  cloud:
    nacos:
      discovery:
#        server-addr: 101.200.82.237:8848
        server-addr: localhost:8848
#        namespace: a2b425a7-92b5-494a-941f-bbfab80e9959
        metadata:
          instance: cc
          version: 1.0
server:
  port: 8084
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
